title: NAM Pack
logo: /assets/img/logo.jpg
description: NAM Pack is a custom distribution pack built to explore the cutting edge in minecraft mods. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
